language: python

python:
  - '2.7'

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - pytest -vv tests/
  - coverage run --source=src tests/

after_success:
  - coveralls