language: python

python:
  - '2.7'

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - pytest -vv tests/
  - coverage run --source=src tests/

after_success:
  - coveralls